### ISSUE TITLE
CMake error string REGEX MATCH

### ISSUE THREAD

**Issue by splashgywastaken** [cmmw/imgui-glfw-glad#1] opened 2023-10-29 11:19 UTC
I get this CMake error while trying to compile example project (or any project that fetches this project)/ CMakeLists file is root folder of the project
`CMake Error at CMakeLists.txt:74 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
`
Got this issue just recently. CMake version is 3.27.7

**Comment by splashgywastaken** [comment] 2023-10-29 11:21
Same issue happens using cmake version 3.28.0-rc3

**Comment by splashgywastaken** [comment] 2023-10-29 11:21
Thought that another cmake version fixes it, but same happens with 3.28.0-rc3

**Comment by cmmw** [comment] 2023-10-29 15:50
Hey, thanks for reporting this problem!

It seems like the curl command does not return any result. 
Can you call the following command in your command line and tell me what response you receive:

`curl -s -D - -X POST -d "generator=c&api=egl%3Dnone&api=gl%3D4.5&profile=gl%3Dcore&api=gles1%3Dnone&profile=gles1%3Dcommon&api=gles2%3Dnone&api=glsc2%3Dnone&api=glx%3Dnone&api=vulkan%3Dnone&api=wgl%3Dnone&options=LOADER" "https://gen.glad.sh/generate"`

As a workaround you can set IGG_GLAD_DOWNLOAD to OFF. The script will then use the included glad loader sources (gl 4.5 core profile).

**Comment by splashgywastaken** [comment] 2023-10-29 17:22
When I'm trying to run this command I get next error (my windows is in another language so I translated the error therefore it may not match with what is listed on the internet):
```
Invoke-WebRequest : Missing argument for "SessionVariable" parameter. Specify parameter with type "System.String" and try again.
line:1 sym:6                                                                                    
+ curl -s -D - -X POST -d "generator=c&api=egl%3Dnone&api=gl%3D4.5&prof ...                        
+      ~~                                                                                          
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException  
    + FullyQualifiedErrorId : MissingArgument,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
And yep, making IGG_GLAD_DOWNLOAD as OFF worked perfectly fine, thanks!

**Comment by cmmw** [comment] 2023-10-29 17:57
In order for curl to work in the windows powershell, you have to use the program name with the extension:

`curl.exe -s -D - -X POST -d "generator=c&api=egl%3Dnone&api=gl%3D4.5&profile=gl%3Dcore&api=gles1%3Dnone&profile=gles1%3Dcommon&api=gles2%3Dnone&api=glsc2%3Dnone&api=glx%3Dnone&api=vulkan%3Dnone&api=wgl%3Dnone&options=LOADER" "https://gen.glad.sh/generate"`

**Comment by splashgywastaken** [comment] 2023-10-29 18:41
Well, if I use it like this it outputs nothing. Seems like it could be a problem on my side but idk

**Comment by cmmw** [comment] 2023-10-29 21:35
That's strange, can you try it in the cmd?

**Comment by cmmw** [comment] 2023-10-31 12:53
I've released a new version (v4.1.0) with better error handling and reporting. If you want you can try this version and check the output of the cmake script. If it's unable to download the glad loader sources it will print the error code/error message reported by curl, it will also automatically use the included version in this case.

**Comment by splashgywastaken** [comment] 2023-10-31 13:08
Sorry for writing so late, but cmd isn't working either. 
The error that's being displayed is this:
```
CMake Warning at cmake-build-debug/_deps/imgui-glfw-glad-glm-src/CMakeLists.txt:80 (message):
  C:/Windows/System32/curl.exe returned: 35
```
Later I'll try to update curl and see what will happen then, if something will be fixed, I'll update here.
But new version works fine, thanks! I think we can close this issue now

**Comment by cmmw** [comment] 2023-10-31 13:48
No problem!

According to curl, error code 35 means there is a problem with the SSL/TLS handshake. I cannot reproduce this behaviour on my machine by sending a simple GET request with curl to https://gen.glad.sh/.

I will close this ticket as it seems to be not a problem with the CMake script.

**Closed as completed by cmmw** 2023-10-31 13:48 UTC
